<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="6" UUID="07549f2b-fe3c-4e6e-b72e-59c4722708fa" created="Wed Apr 01 16:37:27 IST 2020" createdBy="DishaSingh" main="Hook_Default_On_Error" modified="Tue Feb 16 17:40:55 CET 2021" modifiedBy="edbir" project="POC_MVP" version="7.1.1">
    <Script name="Hook_Default_On_Error">
        <ModTime>1613493655092</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[log("FATAL", "Error working with from OpenPages: " + error.message);
throw error.getObject("Exception");]]></parameter>
    </Script>
</MetamergeConfig>